name: Publish and Sign Container Image

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug OIDC token
        run: |
          curl -sLS -o /tmp/token.sh https://raw.githubusercontent.com/sigstore/cosign/main/hack/oidc-token.sh
          bash /tmp/token.sh
          
      - name: Install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.13.1'

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into ghcr.io
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        id: push-step
        uses: docker/build-push-action@master
        with:
          push: true
          context: ./django-keyless-signing
          file: ./django-keyless-signing/Dockerfile
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Sign the container image
        run: |
          echo "Signing image: ghcr.io/${{ github.repository }}@${{ steps.push-step.outputs.digest }}"
          rm -rf ~/.sigstore
          cosign sign --yes ghcr.io/${{ github.repository }}@${{ steps.push-step.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: "1"

      - name: Verify signed container image
        run: cosign verify ghcr.io/${{ github.repository }}@${{ steps.push-step.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: "1"
